### ISSUE TITLE
last month of years problem

### ISSUE THREAD

**Issue by alireza-rou13** [mzangeneh/fullcalendar-shamsi#4]
سلام در آخرین ماه هر سال از 1401 به مشکل میخوریم که ماه دوتایی نمایش میده

**Comment by martian-coder-ir** [comment]
منم این مشکلو دارم ! ماه های اخر همه سالها دو ماه دیده میشه

**Comment by mabbaszadegan** [comment]
وقتی میریم ماه آخر میشه اسفند-فروردین و دیگه دکمه ماه قبل هم کار نمیکنه

**Comment by samangilbert** [comment]
در مورد این مشکل به نتیجه ای رسیدید؟
